### PR TITLE
REP-3139 There are the updates required to operate with Repose v7.3.0.0.

### PR DESCRIPTION
**Pull request by wdschei**
Since this filter is slightly coupled with the Repose internals, whenever a Major or Minor (first or second digit) release is made, there is a potential for incompatibilities. This is one of those cases where a Minor change would break this filter.

### CODE REVIEW

**Comment by tpboudreau-rackspace** [comment]
@wdschei , you are absolutely The Man.

Just got tripped up on this breaking Akka change this morning and was about to get started fixing it here.  Thanks for jumping in and anticipating this.

I'll test out your changes and let you know how it goes.

Thanks again.

**Comment by wdschei** [comment]
No problem. We do what we can.

**Comment by tpboudreau-rackspace** [comment]
Builds clean and passes all my integration tests.  Thanks again.
+1

**Comment by wdschei** [comment]
Great to hear.

**Pull request merged**
